#![doc = "Peripheral access API for SH32F2XX microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDT();
    fn BOD();
    fn RCC();
    fn EXTI0();
    fn EXTI1();
    fn EXTI2();
    fn EXTI3();
    fn MCM_FLT();
    fn MCM_PWM();
    fn ADC();
    fn PCA0();
    fn PCA0_FLT();
    fn CMP2();
    fn CMP0();
    fn CMP1();
    fn EXTI4();
    fn EXTI5();
    fn PWM3();
    fn SPI0();
    fn UART0();
    fn UART1();
    fn PWM4();
    fn TIM7();
    fn TIM8();
    fn EXTI6_7();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 26] = [
    Vector { _handler: WWDT },
    Vector { _handler: BOD },
    Vector { _handler: RCC },
    Vector { _handler: EXTI0 },
    Vector { _handler: EXTI1 },
    Vector { _handler: EXTI2 },
    Vector { _handler: EXTI3 },
    Vector { _handler: MCM_FLT },
    Vector { _handler: MCM_PWM },
    Vector { _handler: ADC },
    Vector { _handler: PCA0 },
    Vector { _reserved: 0 },
    Vector { _handler: PCA0_FLT },
    Vector { _handler: CMP2 },
    Vector { _handler: CMP0 },
    Vector { _handler: CMP1 },
    Vector { _handler: EXTI4 },
    Vector { _handler: EXTI5 },
    Vector { _handler: PWM3 },
    Vector { _handler: SPI0 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _handler: PWM4 },
    Vector { _handler: TIM7 },
    Vector { _handler: TIM8 },
    Vector { _handler: EXTI6_7 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WWDT"]
    WWDT = 0,
    #[doc = "1 - BOD"]
    BOD = 1,
    #[doc = "2 - RCC"]
    RCC = 2,
    #[doc = "3 - EXTI0"]
    EXTI0 = 3,
    #[doc = "4 - EXTI1"]
    EXTI1 = 4,
    #[doc = "5 - EXTI2"]
    EXTI2 = 5,
    #[doc = "6 - EXTI3"]
    EXTI3 = 6,
    #[doc = "7 - MCM_FLT"]
    MCM_FLT = 7,
    #[doc = "8 - MCM_PWM"]
    MCM_PWM = 8,
    #[doc = "9 - ADC"]
    ADC = 9,
    #[doc = "10 - PCA0"]
    PCA0 = 10,
    #[doc = "12 - PCA0_FLT"]
    PCA0_FLT = 12,
    #[doc = "13 - CMP2"]
    CMP2 = 13,
    #[doc = "14 - CMP0"]
    CMP0 = 14,
    #[doc = "15 - CMP1"]
    CMP1 = 15,
    #[doc = "16 - EXTI4"]
    EXTI4 = 16,
    #[doc = "17 - EXTI5"]
    EXTI5 = 17,
    #[doc = "18 - PWM3"]
    PWM3 = 18,
    #[doc = "19 - SPI0"]
    SPI0 = 19,
    #[doc = "20 - UART0"]
    UART0 = 20,
    #[doc = "21 - UART1"]
    UART1 = 21,
    #[doc = "22 - PWM4"]
    PWM4 = 22,
    #[doc = "23 - TIM7"]
    TIM7 = 23,
    #[doc = "24 - TIM8"]
    TIM8 = 24,
    #[doc = "25 - EXTI6_7"]
    EXTI6_7 = 25,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "PCA0"]
pub type Pca0 = crate::Periph<pca0::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Pca0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pca0").finish()
    }
}
#[doc = "PCA0"]
pub mod pca0;
#[doc = "TIM7"]
pub type Tim7 = crate::Periph<tim7::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for Tim7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim7").finish()
    }
}
#[doc = "TIM7"]
pub mod tim7;
#[doc = "TIM8"]
pub type Tim8 = crate::Periph<tim8::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Tim8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim8").finish()
    }
}
#[doc = "TIM8"]
pub mod tim8;
#[doc = "UART0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART0"]
pub mod uart0;
#[doc = "UART1"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4000_1c00>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART1"]
pub mod uart1;
#[doc = "SPI0"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4000_2400>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "SPI0"]
pub mod spi0;
#[doc = "IWDT"]
pub type Iwdt = crate::Periph<iwdt::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Iwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdt").finish()
    }
}
#[doc = "IWDT"]
pub mod iwdt;
#[doc = "WWDT"]
pub type Wwdt = crate::Periph<wwdt::RegisterBlock, 0x4000_3400>;
impl core::fmt::Debug for Wwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt").finish()
    }
}
#[doc = "WWDT"]
pub mod wwdt;
#[doc = "AMOC"]
pub type Amoc = crate::Periph<amoc::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for Amoc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Amoc").finish()
    }
}
#[doc = "AMOC"]
pub mod amoc;
#[doc = "EXTI"]
pub type Exti = crate::Periph<exti::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Exti {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Exti").finish()
    }
}
#[doc = "EXTI"]
pub mod exti;
#[doc = "PWM3"]
pub type Pwm3 = crate::Periph<pwm3::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Pwm3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3").finish()
    }
}
#[doc = "PWM3"]
pub mod pwm3;
#[doc = "PWM4"]
pub type Pwm4 = crate::Periph<pwm4::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for Pwm4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm4").finish()
    }
}
#[doc = "PWM4"]
pub mod pwm4;
#[doc = "GPIOA"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "GPIOA"]
pub mod gpioa;
#[doc = "GPIOB"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x4004_0080>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "GPIOB"]
pub mod gpiob;
#[doc = "GPIOC"]
pub type Gpioc = crate::Periph<gpioc::RegisterBlock, 0x4004_0100>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "GPIOC"]
pub mod gpioc;
#[doc = "MCM"]
pub type Mcm = crate::Periph<mcm::RegisterBlock, 0x4004_0400>;
impl core::fmt::Debug for Mcm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcm").finish()
    }
}
#[doc = "MCM"]
pub mod mcm;
#[doc = "SYSCFG"]
pub type Syscfg = crate::Periph<syscfg::RegisterBlock, 0x4004_0800>;
impl core::fmt::Debug for Syscfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscfg").finish()
    }
}
#[doc = "SYSCFG"]
pub mod syscfg;
#[doc = "RCC"]
pub type Rcc = crate::Periph<rcc::RegisterBlock, 0x4004_0c00>;
impl core::fmt::Debug for Rcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcc").finish()
    }
}
#[doc = "RCC"]
pub mod rcc;
#[doc = "FLASH"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "FLASH"]
pub mod flash;
#[doc = "MACP"]
pub type Macp = crate::Periph<macp::RegisterBlock, 0x4004_1400>;
impl core::fmt::Debug for Macp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Macp").finish()
    }
}
#[doc = "MACP"]
pub mod macp;
#[doc = "ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4004_1800>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "ADC"]
pub mod adc;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "PCA0"]
    pub pca0: Pca0,
    #[doc = "TIM7"]
    pub tim7: Tim7,
    #[doc = "TIM8"]
    pub tim8: Tim8,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "IWDT"]
    pub iwdt: Iwdt,
    #[doc = "WWDT"]
    pub wwdt: Wwdt,
    #[doc = "AMOC"]
    pub amoc: Amoc,
    #[doc = "EXTI"]
    pub exti: Exti,
    #[doc = "PWM3"]
    pub pwm3: Pwm3,
    #[doc = "PWM4"]
    pub pwm4: Pwm4,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "MCM"]
    pub mcm: Mcm,
    #[doc = "SYSCFG"]
    pub syscfg: Syscfg,
    #[doc = "RCC"]
    pub rcc: Rcc,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "MACP"]
    pub macp: Macp,
    #[doc = "ADC"]
    pub adc: Adc,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            pca0: Pca0::steal(),
            tim7: Tim7::steal(),
            tim8: Tim8::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            spi0: Spi0::steal(),
            iwdt: Iwdt::steal(),
            wwdt: Wwdt::steal(),
            amoc: Amoc::steal(),
            exti: Exti::steal(),
            pwm3: Pwm3::steal(),
            pwm4: Pwm4::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            mcm: Mcm::steal(),
            syscfg: Syscfg::steal(),
            rcc: Rcc::steal(),
            flash: Flash::steal(),
            macp: Macp::steal(),
            adc: Adc::steal(),
        }
    }
}
